"""Agregar area, num_locales, anio a empresa

Revision ID: 94d967c5c93e
Revises: db6711993932
Create Date: 2026-09-07 15:17:15.497991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d967c5c93e'
down_revision: Union[str, Sequence[str], None] = 'db6711993932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('empresa', sa.Column('num_locales', sa.Integer(), nullable=True))
    op.add_column('empresa', sa.Column('anio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'anio')
    op.drop_column('empresa', 'num_locales')
    op.drop_column('empresa', 'area')
    # ### end Alembic commands ###
