"""Agregar distrito, razon_social nullable

Revision ID: bc9265af3d81
Revises: 15e1b39f3fb2
Create Date: 2026-09-07 14:42:33.527720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9265af3d81'
down_revision: Union[str, Sequence[str], None] = '15e1b39f3fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('distrito', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'distrito')
    # ### end Alembic commands ###
