"""Quitar unique constraint de ruc

Revision ID: db6711993932
Revises: 84f3fe7e09f8
Create Date: 2026-09-07 15:02:08.906489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6711993932'
down_revision: Union[str, Sequence[str], None] = '84f3fe7e09f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('empresa_ruc_key'), 'empresa', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('empresa_ruc_key'), 'empresa', ['ruc'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
